services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata_urls:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    networks: [app-network]

  bot:
    build:
      context: .
      dockerfile: ./configs/tgbot/Dockerfile
    env_file:
      - ./configs/.env
    volumes:
      - ./configs/.env:/Projects/python/nakama-ideas-manager/configs/.env
      - ./chroma:/Projects/python/nakama-ideas-manager/chroma
    depends_on: [db, chroma]
    networks: [app-network]

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./chroma:/chroma-data
    networks: [app-network]

volumes:
  pgdata_urls:

networks:
  app-network:
    external: false
