services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata_urls:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    networks: [app-network]

  chroma:
    image: chromadb/chroma:0.5
    volumes:
      - ./chroma:/chroma-data

volumes:
  pgdata_links:

networks:
  app-network:
    external: false
